### ISSUE TITLE
Decoder support?

### ISSUE THREAD

**Issue by EvanCarroll** [rust-av/svt-av1-rs#2]
It's not clear from the project or documentation, but this only supports encoding? Should it not also include the decoder? I can provide a patch for this if desired (and would almost prefer to do it if you'd code review).

One question I would have on this is if the decoder is to be supported by this project, should we generate two wrappers with bindgen? This would allow the rust to more closely follow how the C++ dev libs are packaged by the distros?

```
❯ apt-cache search svt-av1
libsvtav1-dev - Scalable Video Technology for AV1 (header files)
libsvtav1dec-dev - Scalable Video Technology for AV1 (libsvtav1dec development files)
libsvtav1enc-dev - Scalable Video Technology for AV1 (libsvtav1enc development files)
```

**Comment by lu-zero** [comment]
If you want to support it you are welcome to contribute :) I'd rather have a single crate for everything though.
